### ISSUE TITLE
Unhandled exception in example/dht_example.dart

### ISSUE THREAD

**Issue by yolkhovyy** [yolkhovyy/dht_dart#1]
e2d010e1c4413d60688743f4a98fc80913e73893

DHTRead failed
handler result
Unhandled exception:
Exception: DHT data read failed
#0      main (file:///home/pi/projects/spikes/dht/example/dht_example.dart:11:27)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

**Comment by yolkhovyy** [comment]
Solved
